"""
URL configuration for openbase_coder_cli_app.
"""

from __future__ import annotations

from django.urls import include, path
from rest_framework.routers import DefaultRouter

from openbase_coder_cli.openbase_coder_cli_app.common import offloaded_view
from openbase_coder_cli.openbase_coder_cli_app.dictation import dictation_session
from openbase_coder_cli.openbase_coder_cli_app.health_warnings import health_warnings
from openbase_coder_cli.openbase_coder_cli_app.notifications import (
    notification_list,
    notification_mark_all_read,
    notification_mark_read,
)
from openbase_coder_cli.openbase_coder_cli_app.skill_settings import (
    skill_sharing_settings,
)
from openbase_coder_cli.openbase_coder_cli_app.sync_daemon_api import (
    sync_conflicts,
    sync_daemon_barrier,
    sync_daemon_conflict_detail,
    sync_daemon_conflicts,
    sync_daemon_conflicts_resolve,
    sync_daemon_held_deletes,
    sync_daemon_hydrate,
    sync_daemon_settings,
    sync_daemon_stale_lock_trash,
    sync_daemon_stale_locks,
    sync_daemon_status,
    sync_daemon_stubs,
    sync_status,
)
from openbase_coder_cli.openbase_coder_cli_app.sync_pairing_api import (
    sync_daemon_available_roots,
    sync_daemon_roots,
    sync_pairing_candidates,
    sync_pairing_folders,
    sync_pairing_hub,
    sync_pairing_hub_folders,
    sync_pairing_join,
    sync_pairing_leave,
    sync_pairing_offer,
)
from openbase_coder_cli.openbase_coder_cli_app.thread_push_api import (
    thread_push,
    thread_push_arrival_detail,
    thread_push_arrivals,
    thread_push_cancel,
    thread_push_release,
    thread_push_target,
)
from openbase_coder_cli.openbase_coder_cli_app.update import (
    update_apply,
    update_status,
)
from openbase_coder_cli.openbase_coder_cli_app.views import (
    agents_md,
    all_project_reports,
    analytics_identify,
    apple_music_playback_entitlement,
    approval_request_detail,
    approval_requests,
    auth_logout,
    auth_refresh_jwt_removed,
    auth_session,
    backend_model_settings,
    boilersync_templates,
    bootstrap_run,
    brain_readiness,
    cartesia_voice_settings,
    claude_auth_settings,
    claude_plugin_settings,
    codex_plugin_settings,
    coding_backend_settings,
    dangerous_confirmation_settings,
    devices_list,
    dispatcher_voice_settings,
    env_settings,
    git_diff,
    global_reports_projects,
    health_check,
    hooks_ingest,
    inbound_call_activate,
    inbound_call_decline,
    ios_app_control,
    ios_logs_upload,
    keep_awake_settings,
    kokoro_tts_download,
    launchctl_ignored_settings,
    launchctl_service_action,
    launchctl_services_list,
    livekit_companion_session,
    livekit_companion_start,
    livekit_room_token,
    livekit_voice_route,
    livekit_voice_route_exit,
    livekit_voice_route_transfer,
    local_stt_download,
    marketplace_routines,
    marketplace_skill_install,
    marketplace_skills,
    memories_list,
    memory_detail,
    onboarding_cloud_state,
    onboarding_status,
    openbase_restart,
    openbase_service_action,
    openbase_services_list,
    plugin_console_registry,
    plugin_detail,
    plugins_list,
    printing_press_catalog,
    printing_press_install,
    project_reports,
    project_reports_action,
    project_reports_download,
    project_reports_file,
    project_reports_tags,
    project_status,
    reasoning_settings,
    recent_projects,
    report_share,
    report_share_grants,
    report_share_revoke_grant,
    routine_detail,
    routine_emit,
    routine_trigger_detail,
    routine_triggers,
    routines_list,
    routines_run_due,
    service_status,
    service_tier_settings,
    skill_approval_request_consume,
    skill_approval_request_detail,
    skill_approval_requests,
    skill_detail,
    skills_auto_link_settings,
    skills_list,
    skills_symlink,
    stt_settings,
    tag_options,
    thread_active_voice,
    thread_activity,
    thread_detail,
    thread_device_sync_conflict_resolve,
    thread_device_sync_conflicts,
    thread_device_sync_status,
    thread_dispatcher,
    thread_favorite,
    thread_interrupt,
    thread_list,
    thread_model_settings,
    thread_name,
    thread_queue_turn,
    thread_start_turn,
    thread_steer_turn,
    thread_sync_conflicts,
    thread_tags,
    tts_settings,
    user_call,
    user_play,
    user_say,
    uv_tool_detail,
    uv_tool_executable_help,
    uv_tools_list,
)
from openbase_coder_cli.openbase_coder_cli_app.voice_model_settings import (
    voice_model_settings,
    voice_model_usage,
)

router = DefaultRouter()

urlpatterns = [
    path("dictation/session/", offloaded_view(dictation_session), name="dictation-session"),
    path("auth/session/", auth_session, name="auth-session"),
    path(
        "auth/refresh-jwt/",
        auth_refresh_jwt_removed,
        name="auth-refresh-jwt-removed",
    ),
    path("auth/logout/", auth_logout, name="auth-logout"),
    path("agents-md/", agents_md, name="agents-md"),
    path("health/", health_check, name="health-check"),
    # ``offloaded_view`` runs these hot read endpoints off Django's shared
    # thread-sensitive ASGI executor so a page's mount-time burst of API
    # calls runs concurrently instead of serializing one at a time. See the
    # helper's docstring in ``openbase_coder_cli_app.common``.
    path("health/warnings/", offloaded_view(health_warnings), name="health-warnings"),
    path("brain-readiness/", brain_readiness, name="brain-readiness"),
    path(
        "features/apple-music-playback/",
        apple_music_playback_entitlement,
        name="apple-music-playback-entitlement",
    ),
    path("diagnostics/ios-logs/", ios_logs_upload, name="ios-logs-upload"),
    path("user/ios-app-control/", ios_app_control, name="ios-app-control"),
    path("devices/", devices_list, name="devices-list"),
    path("onboarding/status/", onboarding_status, name="onboarding-status"),
    # Desktop reaches Openbase Cloud only through this server; both slash forms
    # are accepted because clients differ (see the cloud analytics urls).
    path(
        "openbase/analytics/identify",
        analytics_identify,
        name="analytics-identify",
    ),
    path("openbase/analytics/identify/", analytics_identify),
    path(
        "onboarding/cloud-state/",
        onboarding_cloud_state,
        name="onboarding-cloud-state",
    ),
    path("update/status/", update_status, name="update-status"),
    path("update/apply/", update_apply, name="update-apply"),
    path("threads/", offloaded_view(thread_list), name="thread-list"),
    path("threads/activity/", offloaded_view(thread_activity), name="thread-activity"),
    path(
        "threads/active-voice/",
        offloaded_view(thread_active_voice),
        name="thread-active-voice",
    ),
    path(
        "threads/dispatcher/",
        offloaded_view(thread_dispatcher),
        name="thread-dispatcher",
    ),
    path(
        "threads/push/target/",
        offloaded_view(thread_push_target),
        name="thread-push-target",
    ),
    path(
        "threads/push/arrivals/",
        offloaded_view(thread_push_arrivals),
        name="thread-push-arrivals",
    ),
    path(
        "threads/push/arrivals/<str:operation_id>/",
        offloaded_view(thread_push_arrival_detail),
        name="thread-push-arrival-detail",
    ),
    path(
        "threads/<str:thread_id>/", offloaded_view(thread_detail), name="thread-detail"
    ),
    path(
        "threads/<str:thread_id>/tags/",
        offloaded_view(thread_tags),
        name="thread-tags",
    ),
    path(
        "threads/<str:thread_id>/favorite/",
        offloaded_view(thread_favorite),
        name="thread-favorite",
    ),
    path(
        "threads/<str:thread_id>/name/",
        thread_name,
        name="thread-name",
    ),
    path(
        "threads/<str:thread_id>/push/",
        offloaded_view(thread_push),
        name="thread-push",
    ),
    path(
        "threads/<str:thread_id>/push/cancel/",
        offloaded_view(thread_push_cancel),
        name="thread-push-cancel",
    ),
    path(
        "threads/<str:thread_id>/push/release/",
        thread_push_release,
        name="thread-push-release",
    ),
    path(
        "threads/<str:thread_id>/interrupt/",
        thread_interrupt,
        name="thread-interrupt",
    ),
    path(
        "threads/<str:thread_id>/models/",
        thread_model_settings,
        name="thread-model-settings",
    ),
    path("threads/<str:thread_id>/turns/", thread_start_turn, name="thread-start-turn"),
    path(
        "threads/<str:thread_id>/turns/queue/",
        thread_queue_turn,
        name="thread-queue-turn",
    ),
    path(
        "threads/<str:thread_id>/turns/steer/",
        thread_steer_turn,
        name="thread-steer-turn",
    ),
    # The console fires these alongside every thread open. They ran on
    # Django's single thread-sensitive executor, queued behind git-sync and
    # service-status probes; offloading lets them run concurrently.
    path("notifications/", offloaded_view(notification_list), name="notifications"),
    path(
        "notifications/mark-read/",
        notification_mark_read,
        name="notifications-mark-read",
    ),
    path(
        "notifications/mark-all-read/",
        notification_mark_all_read,
        name="notifications-mark-all-read",
    ),
    path(
        "approval-requests/",
        offloaded_view(approval_requests),
        name="approval-requests",
    ),
    path(
        "approval-requests/<str:request_id>/",
        approval_request_detail,
        name="approval-request-detail",
    ),
    path(
        "skill-approval-requests/",
        skill_approval_requests,
        name="skill-approval-requests",
    ),
    path(
        "skill-approval-requests/<str:request_id>/",
        skill_approval_request_detail,
        name="skill-approval-request-detail",
    ),
    path(
        "skill-approval-requests/<str:request_id>/consume/",
        skill_approval_request_consume,
        name="skill-approval-request-consume",
    ),
    path("routines/", routines_list, name="routines-list"),
    path("routines/run-due/", routines_run_due, name="routines-run-due"),
    path("routines/<str:name>/triggers/", routine_triggers, name="routine-triggers"),
    path(
        "routines/<str:name>/triggers/<str:trigger_id>/",
        routine_trigger_detail,
        name="routine-trigger-detail",
    ),
    path("routines/<str:name>/emit/", routine_emit, name="routine-emit"),
    path("routines/<str:name>/", routine_detail, name="routine-detail"),
    path("hooks/t/<str:token>/", hooks_ingest, name="hooks-ingest"),
    path("user/say/", user_say, name="user-say"),
    path("user/call/", user_call, name="user-call"),
    path("user/play/", user_play, name="user-play"),
    path(
        "inbound-call/activate/",
        inbound_call_activate,
        name="inbound-call-activate",
    ),
    path(
        "inbound-call/decline/",
        inbound_call_decline,
        name="inbound-call-decline",
    ),
    path("projects/recent/", offloaded_view(recent_projects), name="recent-projects"),
    path("projects/status/", offloaded_view(project_status), name="project-status"),
    path("tags/", offloaded_view(tag_options), name="tag-options"),
    path("projects/reports/", offloaded_view(project_reports), name="project-reports"),
    path(
        "projects/reports/all/",
        offloaded_view(all_project_reports),
        name="all-project-reports",
    ),
    path(
        "projects/reports/action/",
        project_reports_action,
        name="project-reports-action",
    ),
    path(
        "projects/reports/global/",
        offloaded_view(global_reports_projects),
        name="global-reports-projects",
    ),
    path(
        "projects/reports/file/",
        project_reports_file,
        name="project-reports-file",
    ),
    path(
        "projects/reports/tags/",
        project_reports_tags,
        name="project-reports-tags",
    ),
    path(
        "projects/reports/download/",
        project_reports_download,
        name="project-reports-download",
    ),
    path(
        "projects/reports/share/",
        report_share,
        name="project-reports-share",
    ),
    path(
        "projects/reports/share/grants/",
        report_share_grants,
        name="project-reports-share-grants",
    ),
    path(
        "projects/reports/share/grants/revoke/",
        report_share_revoke_grant,
        name="project-reports-share-revoke-grant",
    ),
    path("memories/", memories_list, name="memories-list"),
    path("memories/<path:memory_name>/", memory_detail, name="memory-detail"),
    path("skills/", skills_list, name="skills-list"),
    path("skills/settings/", skill_sharing_settings, name="skill-sharing-settings"),
    path(
        "marketplace/skills/",
        marketplace_skills,
        name="marketplace-skills",
    ),
    path(
        "marketplace/skills/install/",
        marketplace_skill_install,
        name="marketplace-skill-install",
    ),
    path(
        "marketplace/routines/",
        marketplace_routines,
        name="marketplace-routines",
    ),
    path(
        "skills/auto-link-personal/",
        skills_auto_link_settings,
        name="skills-auto-link-personal",
    ),
    path("skills/symlink/", skills_symlink, name="skills-symlink"),
    path(
        "skills/printing-press/catalog/",
        printing_press_catalog,
        name="printing-press-catalog",
    ),
    path(
        "skills/printing-press/install/",
        printing_press_install,
        name="printing-press-install",
    ),
    path("skills/<path:skill_name>/", skill_detail, name="skill-detail"),
    path("plugins/", plugins_list, name="plugins-list"),
    path(
        "plugins/console-registry/",
        plugin_console_registry,
        name="plugin-console-registry",
    ),
    path("plugins/<str:plugin_id>/", plugin_detail, name="plugin-detail"),
    path(
        "boilersync/templates/",
        offloaded_view(boilersync_templates),
        name="boilersync-templates",
    ),
    path("tools/uv/", uv_tools_list, name="uv-tools-list"),
    path(
        "tools/uv/<str:tool_name>/executables/<str:executable_name>/help/",
        uv_tool_executable_help,
        name="uv-tool-executable-help",
    ),
    path("tools/uv/<str:tool_name>/", uv_tool_detail, name="uv-tool-detail"),
    path("tools/launchctl/", launchctl_services_list, name="launchctl-services-list"),
    path(
        "settings/launchctl-ignored/",
        launchctl_ignored_settings,
        name="launchctl-ignored-settings",
    ),
    path(
        "settings/dangerous-confirmation/",
        dangerous_confirmation_settings,
        name="dangerous-confirmation-settings",
    ),
    path(
        "settings/keep-awake/",
        keep_awake_settings,
        name="keep-awake-settings",
    ),
    path(
        "settings/openbase-services/",
        openbase_services_list,
        name="openbase-services-list",
    ),
    path(
        "settings/thread-device-sync/",
        thread_device_sync_status,
        name="thread-device-sync-status",
    ),
    path(
        "settings/thread-device-sync/conflicts/",
        thread_device_sync_conflicts,
        name="thread-device-sync-conflicts",
    ),
    path(
        "settings/thread-sync/conflicts/",
        thread_sync_conflicts,
        name="thread-sync-conflicts",
    ),
    path(
        "settings/thread-device-sync/conflicts/<str:thread_id>/resolve/",
        thread_device_sync_conflict_resolve,
        name="thread-device-sync-conflict-resolve",
    ),
    path(
        "settings/restart/",
        openbase_restart,
        name="openbase-restart",
    ),
    path(
        "settings/openbase-services/<str:service_name>/",
        openbase_service_action,
        name="openbase-service-action",
    ),
    path(
        "settings/coding-backend/",
        coding_backend_settings,
        name="coding-backend-settings",
    ),
    path(
        "settings/coding-backend/claude-auth/",
        claude_auth_settings,
        name="coding-backend-claude-auth-settings",
    ),
    path(
        "settings/coding-backend/codex-plugins/",
        codex_plugin_settings,
        name="coding-backend-codex-plugin-settings",
    ),
    path(
        "settings/coding-backend/claude-plugins/",
        claude_plugin_settings,
        name="coding-backend-claude-plugin-settings",
    ),
    path(
        "settings/backend-model/",
        backend_model_settings,
        name="backend-model-settings",
    ),
    path(
        "settings/voice-model/usage/",
        voice_model_usage,
        name="voice-model-usage",
    ),
    path(
        "settings/voice-model/",
        voice_model_settings,
        name="voice-model-settings",
    ),
    path(
        "settings/reasoning/",
        reasoning_settings,
        name="reasoning-settings",
    ),
    path(
        "settings/service-tier/",
        service_tier_settings,
        name="service-tier-settings",
    ),
    path(
        "settings/env/",
        env_settings,
        name="env-settings",
    ),
    path(
        "settings/cartesia-voices/",
        cartesia_voice_settings,
        name="cartesia-voices",
    ),
    path(
        "settings/tts/",
        tts_settings,
        name="tts-settings",
    ),
    path(
        "settings/tts/kokoro/download/",
        kokoro_tts_download,
        name="kokoro-tts-download",
    ),
    path(
        "settings/stt/",
        stt_settings,
        name="stt-settings",
    ),
    path(
        "settings/stt/local/download/",
        local_stt_download,
        name="local-stt-download",
    ),
    path(
        "settings/dispatcher-voice/",
        dispatcher_voice_settings,
        name="dispatcher-voice",
    ),
    path(
        "tools/launchctl/<str:label>/",
        launchctl_service_action,
        name="launchctl-service-action",
    ),
    path(
        "bootstrap/<str:bootstrapper_name>/",
        bootstrap_run,
        name="bootstrap-run",
    ),
    path("git/diff/", git_diff, name="git-diff"),
    path(
        "sync/daemon/settings/",
        offloaded_view(sync_daemon_settings),
        name="sync-daemon-settings",
    ),
    # Pairing and roots can wait on another computer or the service manager,
    # so they run off the shared executor too.
    path(
        "sync/daemon/pairing/candidates/",
        offloaded_view(sync_pairing_candidates),
        name="sync-pairing-candidates",
    ),
    path(
        "sync/daemon/pairing/hub/",
        offloaded_view(sync_pairing_hub),
        name="sync-pairing-hub",
    ),
    path(
        "sync/daemon/pairing/join/",
        offloaded_view(sync_pairing_join),
        name="sync-pairing-join",
    ),
    path(
        "sync/daemon/pairing/leave/",
        offloaded_view(sync_pairing_leave),
        name="sync-pairing-leave",
    ),
    path(
        "sync/daemon/pairing/offer/",
        offloaded_view(sync_pairing_offer),
        name="sync-pairing-offer",
    ),
    path(
        "sync/daemon/pairing/folders/",
        offloaded_view(sync_pairing_folders),
        name="sync-pairing-folders",
    ),
    path(
        "sync/daemon/pairing/hub-folders/",
        offloaded_view(sync_pairing_hub_folders),
        name="sync-pairing-hub-folders",
    ),
    path(
        "sync/daemon/roots/available/",
        offloaded_view(sync_daemon_available_roots),
        name="sync-daemon-available-roots",
    ),
    path(
        "sync/daemon/roots/",
        offloaded_view(sync_daemon_roots),
        name="sync-daemon-roots",
    ),
    path("sync/daemon/status/", sync_daemon_status, name="sync-daemon-status"),
    path("sync/daemon/conflicts/", sync_daemon_conflicts, name="sync-daemon-conflicts"),
    path(
        "sync/daemon/conflicts/<int:conflict_id>/",
        offloaded_view(sync_daemon_conflict_detail),
        name="sync-daemon-conflict-detail",
    ),
    path(
        "sync/daemon/stale-locks/",
        offloaded_view(sync_daemon_stale_locks),
        name="sync-daemon-stale-locks",
    ),
    path(
        "sync/daemon/stale-locks/trash/",
        offloaded_view(sync_daemon_stale_lock_trash),
        name="sync-daemon-stale-lock-trash",
    ),
    path(
        "sync/daemon/held-deletes/",
        offloaded_view(sync_daemon_held_deletes),
        name="sync-daemon-held-deletes",
    ),
    path(
        "sync/daemon/conflicts/resolve/",
        offloaded_view(sync_daemon_conflicts_resolve),
        name="sync-daemon-conflicts-resolve",
    ),
    path("sync/daemon/barrier/", sync_daemon_barrier, name="sync-daemon-barrier"),
    path("sync/daemon/stubs/", sync_daemon_stubs, name="sync-daemon-stubs"),
    path("sync/daemon/hydrate/", sync_daemon_hydrate, name="sync-daemon-hydrate"),
    # Daemon-backed routes in the shapes the phone apps decode.
    path("sync/status/", sync_status, name="sync-status"),
    path("sync/conflicts/", sync_conflicts, name="sync-conflicts"),
    path(
        "sync/conflicts/resolve/",
        sync_daemon_conflicts_resolve,
        name="sync-conflicts-resolve",
    ),
    path("status/", offloaded_view(service_status), name="service-status"),
    path(
        "livekit-companion-session/",
        livekit_companion_session,
        name="livekit-companion-session",
    ),
    path(
        "livekit-companion-start/",
        livekit_companion_start,
        name="livekit-companion-start",
    ),
    path("livekit-room-token/", livekit_room_token, name="livekit-room-token"),
    path("livekit-voice-route/", livekit_voice_route, name="livekit-voice-route"),
    path(
        "livekit-voice-route/exit/",
        livekit_voice_route_exit,
        name="livekit-voice-route-exit",
    ),
    path(
        "livekit-voice-route/transfer/",
        livekit_voice_route_transfer,
        name="livekit-voice-route-transfer",
    ),
    path("", include(router.urls)),
]
